Fix crash while exiting/rotating app
java.lang.IllegalArgumentException: Parcel: unknown type for value Song(id=[REDACTED], title=[REDACTED], artist=[REDACTED], imgUri=[REDACTED], filePath=[REDACTED], fileName=[REDACTED])

Instead of using rememberSaveable, load songs normally